routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('test', 'TestController@test');
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// UsersController
Route::get('users', 'UsersController@index');
Route::post('users', 'UsersController@store');
Route::delete('users', 'UsersController@destroy');

// CustomersController
Route::get('customers', 'CustomersController@index');
Route::post('customers', 'CustomersController@store');
Route::delete('customers', 'CustomersController@destroy');

// ProjectsController
Route::get('projects', 'ProjectsController@index');
Route::post('projects', 'ProjectsController@store');
Route::delete('projects', 'ProjectsController@destroy');

// QuestionCategoryController
Route::get('question_categories', 'QuestionCategoryController@index');
Route::post('question_categories', 'QuestionCategoryController@store');
Route::delete('question_categories', 'QuestionCategoryController@destroy');

// QuestionsController
Route::get('questions', 'QuestionsController@index');
Route::post('questions', 'QuestionsController@store');
Route::delete('questions', 'QuestionsController@destroy');

// FeedbackRoundsController
Route::get('rounds', 'FeedbackRoundsController@index');
Route::post('rounds', 'FeedbackRoundsController@store');
Route::delete('rounds', 'FeedbackRoundsController@destroy');

// FeedbackController
Route::get('feedback', 'FeedbackController@index');
Route::post('feedback', 'FeedbackController@store');
Route::delete('feedback', 'FeedbackController@destroy');

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $fillable = [
        'name',
    ];
    // Accessors
    public function getCustomerNamesAttribute(){
        return $this->customers ? implode(', ', $this->customers->pluck('name')->toArray()) : NULL ;
    }

    // Relations
    public function customers(){
        return $this->belongsToMany('App\Models\Customer', 'project_customer');
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Project;

class ProjectsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        return view('projects.index');
    }
    public function store(Request $request){
        // dump($request);return;   
        $project = Project::findOrNew($request->id);
        $project->fill($request->all());
        $project->save();
        $project->customers()->sync($request->customers);
        toastr()->success('Created Successfully');
        return back();
    }
    public function destroy(Request $request){
        // TODO validation and authorization
        $project = Project::find($request->id);
        $project->delete();
        toastr()->success('Deleted Successfully');
        return back();
    }
}

resources/views/projects/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Projects</h1>
@stop

@section('content')
<div class="col-md-10 col-xs-offset-1">
    {{-- Listing all project --}}
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Projects</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width: 10px">SN</th>
                        <th>Name</th>
                        <th>Customers</th>
                        <th>Action</th>
                    </tr>
                    @foreach (App\Models\Project::all() as $project)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $project->name }}</td>
                        <td>{{ $project->customer_names }}</td>
                        <td>
                            <button type="button" class="btn btn-xs" title="Delete Project" data-toggle="modal"
                                data-target="#deleteModal" data-id="{{ $project->id }}">
                                <i class="fa fa-trash"></i>
                            </button>
                            <a href="{{ url('projects')}}/{{$project->id }}" class="btn btn-xs" title="Edit Project">
                                <i class="fa fa-pencil"></i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    {{-- End of project --}}

    {{-- Add new project --}}

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Add New Project</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" action="{{ url('projects') }}" method="post">
            @csrf
            <div class="row">
                <div class="box-body">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Name</label>
                            <input type="text" name="name" class="form-control" id="exampleInputEmail1"
                                placeholder="Enter Project Name">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Customers</label>
                            <select id="customers" name="customers[]" class="form-control" multiple>
                                @foreach (App\Models\Customer::all() as $customer)
                                <option value="{{ $customer->id }}">{{ $customer->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </form>
    </div>
    {{-- End of add new project --}}
</div>

@include('modals.delete', ['url' => url('projects')])
@stop
@push('js')
<script>
    $(document).ready(function () {
        $("#customers").select2();
    });
</script>
@endpush