routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('test', 'TestController@test');
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// UsersController
Route::get('users', 'UsersController@index');
Route::post('users', 'UsersController@store');
Route::delete('users', 'UsersController@destroy');

// CustomersController
Route::get('customers', 'CustomersController@index');
Route::post('customers', 'CustomersController@store');
Route::delete('customers', 'CustomersController@destroy');

// ProjectsController
Route::get('projects', 'ProjectsController@index');
Route::post('projects', 'ProjectsController@store');
Route::delete('projects', 'ProjectsController@destroy');

// QuestionCategoryController
Route::get('question_categories', 'QuestionCategoryController@index');
Route::post('question_categories', 'QuestionCategoryController@store');
Route::delete('question_categories', 'QuestionCategoryController@destroy');

// QuestionsController
Route::get('questions', 'QuestionsController@index');
Route::post('questions', 'QuestionsController@store');
Route::delete('questions', 'QuestionsController@destroy');

// FeedbackRoundsController
Route::get('rounds', 'FeedbackRoundsController@index');
Route::post('rounds', 'FeedbackRoundsController@store');
Route::delete('rounds', 'FeedbackRoundsController@destroy');

// FeedbackController
Route::get('feedback', 'FeedbackController@index');
Route::post('feedback', 'FeedbackController@store');
Route::delete('feedback', 'FeedbackController@destroy');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'permissions' => 'array',
    ];

    // Accessors
    public function getPermissionNamesAttribute(){
        return $this->permissions ? implode(', ', $this->permissions) : NULL;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        return view('users.index');
    }
    public function store(Request $request){
        $user = User::findOrNew($request->id);
        $user->fill($request->all());
        $user->password = bcrypt($request->password);
        $user->permissions = $request->permissions;
        $user->save();
        toastr()->success('Created Successfully');
        return back();
    }
    public function destroy(Request $request){
        // TODO validation and authorization
        $user = User::find($request->id);
        $user->delete();
        toastr()->success('Deleted Successfully');
        return back();
    }
}

resources/views/users/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Users</h1>
@stop

@section('content')
<div class="col-md-10 col-xs-offset-1">
    {{-- Listing all user --}}
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Users</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width: 10px">SN</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Permissions</th>
                        <th>Action</th>
                    </tr>
                    @foreach (App\Models\User::all() as $user)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->permission_names }}</td>
                        <td>
                            <button type="button" class="btn btn-xs" title="Delete User" data-toggle="modal"
                                data-target="#deleteModal" data-id="{{ $user->id }}">
                                <i class="fa fa-trash"></i>
                            </button>
                            
                            <a href="{{ url('users')}}/{{$user->id }}" class="btn btn-xs" title="Edit User">
                                <i class="fa fa-pencil"></i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    {{-- End of user --}}

    {{-- Add new user --}}

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Add New User</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" action="{{ url('users') }}" method="post">
            @csrf
            <div class="row">
                <div class="box-body">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Name</label>
                            <input type="text" name="name" class="form-control" id="exampleInputEmail1"
                                placeholder="Enter User Name">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Password</label>
                            <input type="text" name="password" class="form-control" id="exampleInputEmail1"
                                placeholder="Enter Password">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Email</label>
                            <input type="text" name="email" class="form-control" id="exampleInputEmail1"
                                placeholder="Enter User Email">
                        </div>
                        <div class="form-group">
                            <label>Permissions</label>
                            <select id="permissions" name="permissions[]" class="form-control" multiple>
                                @foreach (App\Models\Permission::all() as $permission)
                                <option>{{ $permission->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </form>
    </div>
    {{-- End of add new user --}}
</div>

@include('modals.delete', ['url' => url('users')])
@stop
@push('js')
<script>
    $(document).ready(function () {
        $("#permissions").select2();
    });
</script>
@endpush