routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('test', 'TestController@test');
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// UsersController
Route::get('users', 'UsersController@index');
Route::post('users', 'UsersController@store');
Route::delete('users', 'UsersController@destroy');

// CustomersController
Route::get('customers', 'CustomersController@index');
Route::post('customers', 'CustomersController@store');
Route::delete('customers', 'CustomersController@destroy');

// ProjectsController
Route::get('projects', 'ProjectsController@index');
Route::post('projects', 'ProjectsController@store');
Route::delete('projects', 'ProjectsController@destroy');

// QuestionCategoryController
Route::get('question_categories', 'QuestionCategoryController@index');
Route::post('question_categories', 'QuestionCategoryController@store');
Route::delete('question_categories', 'QuestionCategoryController@destroy');

// QuestionsController
Route::get('questions', 'QuestionsController@index');
Route::post('questions', 'QuestionsController@store');
Route::delete('questions', 'QuestionsController@destroy');

// FeedbackRoundsController
Route::get('rounds', 'FeedbackRoundsController@index');
Route::post('rounds', 'FeedbackRoundsController@store');
Route::delete('rounds', 'FeedbackRoundsController@destroy');

// FeedbackController
Route::get('feedback', 'FeedbackController@index');
Route::post('feedback', 'FeedbackController@store');
Route::delete('feedback', 'FeedbackController@destroy');

app/Models/FeedbackRound.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class FeedbackRound extends Model
{
    protected $fillable = [
        'name',
    ];

    // Accessors

    public function getQuestionCategoryNamesAttribute(){
        return $this->questionCategories ? implode(', ', $this->questionCategories->pluck('name')->toArray()) : NULL ;
    }

    // Relations

    public function questionCategories(){
        return $this->belongsToMany('App\Models\QuestionCategory');
    }
}

resources/views/rounds/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1>Feedback Rounds</h1>
@stop

@section('content')
<div class="col-md-10 col-xs-offset-1">
    {{-- Listing all round --}}
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Feedback Rounds</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width: 10px">SN</th>
                        <th>Name</th>
                        <th>QuestionCategories</th>
                        <th>Action</th>
                    </tr>
                    @foreach (App\Models\FeedbackRound::all() as $round)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $round->name }}</td>
                        <td>{{ $round->question_category_names }}</td>
                        <td>
                            <button type="button" class="btn btn-xs" title="Delete FeedbackRound" data-toggle="modal"
                                data-target="#deleteModal" data-id="{{ $round->id }}">
                                <i class="fa fa-trash"></i>
                            </button>
                            <a href="{{ url('rounds')}}/{{$round->id }}" class="btn btn-xs" title="Edit FeedbackRound">
                                <i class="fa fa-pencil"></i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    {{-- End of round --}}

    {{-- Add new round --}}

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Add New FeedbackRound</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" action="{{ url('rounds') }}" method="post">
            @csrf
            <div class="row">
                <div class="box-body">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Name</label>
                            <input type="text" name="name" class="form-control" id="exampleInputEmail1"
                                placeholder="Enter FeedbackRound Name">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Question Categories</label>
                            <select id="question_categories" name="question_categories[]" class="form-control" multiple>
                                @foreach (App\Models\QuestionCategory::all() as $question_category)
                                <option value="{{ $question_category->id }}">{{ $question_category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Add</button>
            </div>
        </form>
    </div>
    {{-- End of add new round --}}
</div>

@include('modals.delete', ['url' => url('rounds')])
@stop
@push('js')
<script>
    $(document).ready(function () {
        $("#question_categories").select2();
    });
</script>
@endpush